---
postgresql_version: "9.5"
postgresql_version_undotted: "{{ postgresql_version | replace('.', '') }}"
postgresql_repo:
  CentOS: "https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-2.noarch.rpm"
  RedHat: "https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/pgdg-redhat95-9.5-2.noarch.rpm"
# default user/password omitted so that default values don't leak to every environment by accident:
#postgresql_avop_user: set this in environment specific vars
#postgresql_avop_password: set this in environment specific vars
#postgresql_avop_database: set this in environment specific vars
postgresql_data_directory: "/var/lib/pgsql/{{ postgresql_version }}/data"
