postgres:
    image: postgres:9.4
    ports:
        - "5432:5432"
    expose:
        - "5432"
    environment:
        POSTGRES_USER: avopfi
        POSTGRES_PASSWORD: avopfi
        POSTGRES_DB: avopfi