---
- name: install packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - httpd
    - mod_ssl
    - openssl

- name: shibboleth repo
  copy:
    src: shibboleth.repo
    dest: "/etc/yum.repos.d/shibboleth.repo"
    owner: root
    group: root
    mode: 0644

- name: install shibboleth
  yum:
    name: shibboleth # was shibboleth.x86_64
    state: present
    update_cache: yes

- name: shibboleth configuration directory
  file: path=/etc/shibboleth state=directory owner=shibd group=shibd mode=0755

- name: shibboleth metadata partners directory
  file: path=/etc/shibboleth/partners state=directory owner=shibd group=shibd mode=0755

- name: fetch haka test certificate
  get_url:
    dest: "/etc/shibboleth/{{ haka_cert_file }}"
    url: "{{ haka_cert_url }}"
  notify:
    - restart shibboleth service

- name: fetch haka metadata
  get_url:
    dest: "/etc/shibboleth/{{ haka_metadata_file }}"
    url: "{{ haka_metadata_url }}"
  notify:
    - restart shibboleth service

- name: shibboleth configuration files
  copy:
    dest: "/etc/shibboleth/{{ item }}"
    src: "shibboleth/{{ item }}"
    mode: 0644
    owner: shibd
    group: shibd
  with_items:
    - attribute-map.xml
    - attribute-policy.xml
  notify:
    - restart shibboleth service

- name: copy ssl certificate
  copy:
    dest: "/etc/pki/tls/certs/local.avop.fi.cert"
    src: "cert/local.avop.fi.cert"
    mode: 0640
    owner: shibd
    group: shibd
  when: environment_id != "prod"
  notify:
    - restart httpd service

- name: copy ssl certificate key
  copy:
    dest: "/etc/pki/tls/private/local.avop.fi.key"
    src: "cert/local.avop.fi.key"
    mode: 0640
    owner: shibd
    group: shibd
  when: environment_id != "prod"
  notify:
    - restart httpd service

- name: shibboleth configuration templates
  template:
    dest: "/etc/shibboleth/shibboleth2.xml"
    src: "shibboleth/shibboleth2.xml.j2"
    mode: 0644
    owner: shibd
    group: shibd
  notify:
    - restart shibboleth service

- name: shibboleth service
  service:
    name: shibd
    state: started
    enabled: yes

- name: apache shibboleth configuration
  copy:
    dest: "/etc/httpd/conf.d/shib_apache.conf"
    src: "apache/shib_apache.conf"
    mode: 0644
    owner: root
    group: root
  notify:
    - restart httpd service

- name: apache site configuration
  template:
    dest: "/etc/httpd/conf.d/avopfi.conf"
    src: "apache/avopfi.conf.j2"
    mode: 0644
    owner: root
    group: root
  notify:
    - restart httpd service

- name: apache site configuration
  template:
    dest: "/etc/httpd/conf.d/kandipalaute.conf"
    src: "apache/kandipalaute.conf.j2"
    mode: 0644
    owner: root
    group: root
  notify:
    - restart httpd service

- name: httpd service
  service:
    name: httpd
    enabled: yes
    state: started
