---
- name: service user
  user:
    name: "{{ avop_service_user }}"
    comment: "Avop Service User"
    password: "*"
    createhome: yes

- name: set SELinux to permissive
  selinux: policy=targeted state=permissive

- name: install openjdk 
  yum:
    name: java-1.8.0-openjdk
    state: present
  when: java_provider == "openjdk"

- name: download oraclejdk
  command: 'wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" {{java_url}} creates={{java_archive}}'
  when: java_provider == "oracle"

- name: unpack oraclejdk
  command: 'tar -zxf {{java_archive}} -C {{java_folder}} creates={{java_name}}'
  when: java_provider == "oracle"

- name: fix oracle ownership
  file: state=directory path={{java_name}} owner=root group=root recurse=yes
  when: java_provider == "oracle"

- name: make java available for system
  command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'
  when: java_provider == "oracle"

- name: clean up downloaded oracle jdk file
  file: state=absent path={{java_archive}}
  when: java_provider == "oracle"

- name: tomcat directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ avop_service_user }}"
    group: "{{ avop_service_user }}"
    mode: 0755
  with_items:
    - "/home/{{ avop_service_user }}/download"
    - "/home/{{ avop_service_user }}/tomcat"

- name: download tomcat
  get_url:
    url: "{{ tomcat_url }}"
    dest: "/home/{{ avop_service_user }}/download/tomcat.tar.gz"
  become: yes
  become_user: "{{ avop_service_user }}"

- name: unpack tomcat
  unarchive:
    src: "/home/{{ avop_service_user }}/download/tomcat.tar.gz"
    dest: "/home/{{ avop_service_user }}/tomcat"
    copy: no
    creates: "/home/{{ avop_service_user }}/tomcat/apache-tomcat-{{ tomcat_version}}/bin/catalina.sh"
  become: yes
  become_user: "{{ avop_service_user }}"

- name: tomcat symlink
  file:
    src: "/home/{{ avop_service_user }}/tomcat/apache-tomcat-{{ tomcat_version}}"
    dest: "/home/{{ avop_service_user }}/tomcat/current"
    state: link
    owner: "{{ avop_service_user }}"
    group: "{{ avop_service_user }}"

- name: tomcat server.xml
  template:
    src: server.xml.j2
    dest: "/home/{{ avop_service_user }}/tomcat/current/conf/server.xml"
    mode: 0644
    owner: "{{ avop_service_user }}"
    group: "{{ avop_service_user }}"
  notify:
    - restart avop-tomcat service

- name: tomcat setenv.sh
  template:
    src: setenv.sh.j2
    dest: "/home/{{ avop_service_user }}/tomcat/current/bin/setenv.sh"
    mode: 0755
    owner: "{{ avop_service_user }}"
    group: "{{ avop_service_user }}"
  notify:
    - restart avop-tomcat service

- name: tomcat unit file
  template:
    src: avop-tomcat.service.j2
    dest: "/etc/systemd/system/avop-tomcat.service"
    mode: 0644
    owner: root
    group: root

- name: tomcat service
  service:
    name: avop-tomcat
    state: started
    enabled: yes
