---
- name: restart postgresql service
  service:
    name: "postgresql-{{ postgresql_version }}"
    state: restarted

- name: reload postgresql service
  service:
    name: "postgresql-{{ postgresql_version }}"
    state: reloaded
