---
apache:
  server_name: "avop.fi"
  certificate: "TODO.cert"
  certificate_key: "TODO.key"
  appserver: "localhost"
postgresql_avop_database: avop
postgresql_avop_user: "{{ vault_postgresql_avop_user }}"
postgresql_avop_password: "{{ vault_postgresql_avop_password }}"
postgresql_data_directory: "/data/pgsql/{{ postgresql_version }}/data"
