---
- hosts: frontend
  become: yes
  become_user: root
  vars_files:
    - "vars/environment/{{ environment_id }}.yml"
    - "vars/environment/{{ environment_id }}_vault.yml"
  roles:
    - role: apache
      tags: [ 'apache' ]

- hosts: backend
  vars_files:
    - "vars/environment/{{ environment_id }}.yml"
    - "vars/environment/{{ environment_id }}_vault.yml"
  become: yes
  become_user: root
  roles:
    - role: backend
      tags: [ 'backend' ]

- hosts: postgresql
  vars_files:
    - "vars/environment/{{ environment_id }}.yml"
    - "vars/environment/{{ environment_id }}_vault.yml"
  become: yes
  become_user: root
  roles:
    - role: postgresql
      tags: [ 'postgresql' ]
