---
- name: install pgdg repo
  yum:
    name: "{{ postgresql_repo[ansible_distribution] }}"
    state: present

- name: install postgresql packages
  yum: # dockerfile disables gpg check, should we?
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - postgresql{{ postgresql_version_undotted }}-server
    - postgresql{{ postgresql_version_undotted }}
    - postgresql{{ postgresql_version_undotted }}-contrib
    - postgresql{{ postgresql_version_undotted }}-plperl
    - postgresql{{ postgresql_version_undotted }}-devel

- name: create postgresql data directory
  file:
    path: "{{ postgresql_data_directory }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  when: postgresql_data_directory is defined

- name: set postgresql data directory
  lineinfile:
    dest: /usr/lib/systemd/system/postgresql-9.5.service
    line: "Environment=PGDATA={{ postgresql_data_directory }}/"
    regexp: "^Environment=PGDATA=.*"
  register: postgresql_unitfile
  when: postgresql_data_directory is defined

- name: reload systemd
  command: systemctl daemon-reload
  when: postgresql_unitfile.changed

- name: install ansible dependencies
  yum:
    name: python-psycopg2
    state: present

- name: get generated locales
  shell: "locale -a"
  register: localelist
  changed_when: False

- name: "generate fi_FI.UTF-8 locale"
  shell: "localedef -i fi_FI -f UTF-8 fi_FI.UTF-8"
  when: "not 'fi_FI.utf8' in localelist.stdout_lines"

- name: "init postgresql cluster"
  shell: "/usr/pgsql-{{ postgresql_version }}/bin/initdb -E UTF-8 --locale fi_FI.UTF-8 -D {{ postgresql_data_directory }}"
  args:
    creates: "{{ postgresql_data_directory }}/PG_VERSION"
  become: yes
  become_user: postgres

- name: postgresql configuration
  template:
    src: "postgresql.conf.j2"
    dest: "{{ postgresql_data_directory }}/postgresql.conf"
    mode: 0644
    owner: postgres
    group: postgres
  notify:
    - restart postgresql service

- name: pg_hba
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_data_directory }}/pg_hba.conf"
    mode: 0644
    owner: postgres
    group: postgres
  notify:
    - reload postgresql service

- name: postgresql service
  service:
    name: "postgresql-{{ postgresql_version }}"
    state: started
    enabled: yes

- name: database user
  postgresql_user:
    user: "{{ postgresql_avop_user }}"
    password: "{{ postgresql_avop_password }}"
  become: yes
  become_user: postgres

- name: application database
  postgresql_db:
    name: "{{ postgresql_avop_database }}"
    owner: "{{ postgresql_avop_user }}"
  become: yes
  become_user: postgres
